version: '3.1'

volumes: 
  db-data:

services:
  speak-easy-db:
    image: postgres:14.2-alpine
    container_name: speak-easy-db
    volumes:
      - db-data:/var/lib/postgresql/data   
    env_file:
      - .env
    ports:
      - "5434:5432"

  speak-easy-api:
    build: .
    container_name: speak-easy-api
    user: node
    env_file:
       - .env
    volumes:
       - ./:/home/node/app
    ports: 
       - "3001:3000"




     
